function NIRS_HDM = nirs_run_NIRS_HDM_cfg
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Configuration NIRS Hemodynamic Modeling HDM
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

spmmat         = cfg_files; %Select NIRS.mat for this subject
spmmat.name    = 'Select SPM.mat (for BOLD)'; % The displayed name
spmmat.tag     = 'spmmat';       %file names
spmmat.filter = 'mat';
spmmat.ufilter = '^SPM.mat$';
spmmat.num     = [1 1];     % Number of inputs required
spmmat.help    = {'Select SPM.mat of BOLD estimation for this subject (or group).'};

spmmat_ASL         = cfg_files;
spmmat_ASL.name    = 'Select SPM.mat (for ASL)'; % The displayed name
spmmat_ASL.tag     = 'spmmat_ASL';       %file names
spmmat_ASL.filter = 'mat';
spmmat_ASL.ufilter = '^SPM.mat$';
spmmat_ASL.num     = [1 1];     % Number of inputs required
spmmat_ASL.help    = {'Select SPM.mat of ASL estimation for this subject (or group).'};

BOLD           = cfg_branch;
BOLD.name      = 'BOLD only';
BOLD.tag       = 'BOLD';
BOLD.val       = {spmmat};
BOLD.help      = {''};

ASL           = cfg_branch;
ASL.name      = 'ASL only';
ASL.tag       = 'ASL';
ASL.val       = {spmmat_ASL};
ASL.help      = {''};

BOLD_ASL           = cfg_branch;
BOLD_ASL.name      = 'BOLD and ASL';
BOLD_ASL.tag       = 'BOLD_ASL';
BOLD_ASL.val       = {spmmat spmmat_ASL};
BOLD_ASL.help      = {''};

spmmat_HbO         = cfg_files;
spmmat_HbO.name    = 'Select SPM.mat (for HbO)'; % The displayed name
spmmat_HbO.tag     = 'spmmat_HbO';       %file names
spmmat_HbO.filter = 'mat';
spmmat_HbO.num     = [1 1];     % Number of inputs required
spmmat_HbO.help    = {'Select SPM_nirs matrix of HbO estimation for this subject.'};

spmmat_HbR         = cfg_files;
spmmat_HbR.name    = 'Select SPM.mat (for HbR)'; % The displayed name
spmmat_HbR.tag     = 'spmmat_HbR';       %file names
spmmat_HbR.filter = 'mat';
spmmat_HbR.num     = [1 1];
spmmat_HbR.help    = {'Select SPM_nirs matrix of HbR estimation for this subject.'};

ch_num_avg         = cfg_entry;
ch_num_avg.name    = 'Channel identification numbers';
ch_num_avg.tag     = 'ch_num_avg';
ch_num_avg.strtype = 'r';
ch_num_avg.num     = [1 Inf];
ch_num_avg.help    = {'Enter channel numbers to be averaged over as a '
    'Matlab row vector, instead of map_file.'}';


%Select view
view         = cfg_entry;
view.name    = 'View';
view.tag     = 'view';
view.strtype = 'r';
view.num     = [1 Inf];
view.val     = {5};
view.help    = {['Enter view.  ',...
    '1: ventral  ',...
    '2: dorsal  ',...
    '3: right  ',...
    '4: left  ',...
    '5: frontal  ',...
    '6: occipital']}; % help text displayed

% %Select map of interest
map_file         = cfg_files;
map_file.name    = 'Select statistical map'; % The displayed name
map_file.tag     = 'map_file';
map_file.filter  = 'mat';
map_file.num     = [1 1];     % Number of inputs required
map_file.help    = {'Select statistical map of interest (file '
    'containing SPM_nirs (for group) or cinterp_SPM_nirs '
    'structure (for individual) ) - used to select channel '
    'with nearest projected distance to statistical map maximum.'}'; % help text displayed


stat_map_mode      = cfg_branch;
stat_map_mode.name      = 'Stat map channel selection mode';
stat_map_mode.tag       = 'stat_map_mode';
stat_map_mode.val       = {map_file};
stat_map_mode.help      = {'Channel selection via maximum of statistical map.'};

ch_avg_mode      = cfg_branch;
ch_avg_mode.name      = 'Channel selection by average';
ch_avg_mode.tag       = 'ch_avg_mode';
ch_avg_mode.val       = {ch_num_avg};
ch_avg_mode.help      = {'Channel selection via maximum of statistical map.'};

ch_mode           = cfg_choice;
ch_mode.name      = 'Channel Selection Mode';
ch_mode.tag       = 'ch_mode';
ch_mode.values    = {stat_map_mode ch_avg_mode};
ch_mode.val       = {ch_avg_mode};
ch_mode.help      = {'Choose channel selection mode: (1) take max of a '
    'statistical map (2) specify channels to be averaged over.'}';

downsamplingFactor1      = cfg_entry;
downsamplingFactor1.tag  = 'downsamplingFactor1';
downsamplingFactor1.name = 'Downsampling Factor';
downsamplingFactor1.val = {5};
downsamplingFactor1.strtype = 'r';
downsamplingFactor1.num     = [1 1];
downsamplingFactor1.help    = {'Specify downsampling factor of time series.'};

rescalingFactor1      = cfg_entry;
rescalingFactor1.tag  = 'rescalingFactor1';
rescalingFactor1.name = 'Rescaling Factor';
rescalingFactor1.val = {0.05};
rescalingFactor1.strtype = 'r';
rescalingFactor1.num     = [1 1];
rescalingFactor1.help    = {'Specify rescaling factor.'};

%File for channel coregistration 'preproc_info' generated by NIRS_SPM
NIRS_SPM_Coregistration_Channels         = cfg_files;
NIRS_SPM_Coregistration_Channels.name    = 'Select file of coregistration info';
NIRS_SPM_Coregistration_Channels.tag     = 'NIRS_SPM_Coregistration_Channels';
NIRS_SPM_Coregistration_Channels.filter  = 'mat';
NIRS_SPM_Coregistration_Channels.num     = [1 1];
NIRS_SPM_Coregistration_Channels.help    = {'Select file of channel '
    'coregistration ''preproc_info'' generated by NIRS_SPM.'}';

HbO_HbR            = cfg_branch;
HbO_HbR.name      = 'HbO+HbR';
HbO_HbR.tag       = 'HbO_HbR';
HbO_HbR.val       = {ch_mode spmmat_HbO spmmat_HbR NIRS_SPM_Coregistration_Channels ...
    view downsamplingFactor1 rescalingFactor1};
HbO_HbR.help      = {'HbO and HbR HDM estimation'};

Modalities           = cfg_choice;
Modalities.name      = 'Modalities: BOLD, BOLD + ASL estimation, ASL only, HbO+HbR:';
Modalities.tag       = 'Modalities';
%Modalities.labels    = {'BOLD' 'BOLD + ASL' 'ASL' 'HbO+HbR'};
Modalities.values    = {BOLD BOLD_ASL ASL HbO_HbR}; %{BOLDchoice spmmat_ASL}; %{'BOLD' 'BOLD + ASL'};
Modalities.val       = {HbO_HbR}; %{BOLD_ASL}; %{spmmat_ASL};
Modalities.help      = {'Choose data type: BOLD, BOLD + ASL, ASL only, HbO+HbR'}; %, HbO+HbR, HbO+HbR+speckle for hemodynamic parameters estimation'};

Model_Choice           = cfg_menu;
Model_Choice.name      = 'Choice of Model';
Model_Choice.tag       = 'Model_Choice';
Model_Choice.labels    = {'Buxton-Friston' 'Zheng-Mayhew' 'Boas-Huppert'};
Model_Choice.values    = {0,1,2};
Model_Choice.val       = {0};
%Model_Choice.def  = @(val)nirs_get_defaults('readNIRS.boxy1.save_bin_dot', val{:});
Model_Choice.help      = {'Choose hemodynamic model: Buxton-Friston, '
    'Zheng-Mayhew, or 1-Compartment Boas-Huppert Model'}';

Stimuli     = cfg_entry;
Stimuli.name    = 'Stimuli identification numbers';
Stimuli.tag     = 'Stimuli';
Stimuli.strtype = 'r';
Stimuli.val     = {1};
Stimuli.num     = [0 Inf];
Stimuli.help    = {'Enter stimuli numbers to include as a Matlab row '
    'vector (get from the design matrix associated with the data file)'}';

% Executable Branch
NIRS_HDM      = cfg_exbranch;
NIRS_HDM.name = 'NIRS Hemodynamic Modelling';
NIRS_HDM.tag  = 'NIRS_HDM';
NIRS_HDM.val  = {Modalities Model_Choice Stimuli};
NIRS_HDM.prog = @nirs_run_NIRS_HDM;
NIRS_HDM.vout = @nirs_cfg_vout_NIRS_HDM;
NIRS_HDM.help = {'NIRS_SPM Hemodynamic Modeling.'};

function vout = nirs_cfg_vout_NIRS_HDM(job)
vout = cfg_dep;
vout.sname      = 'NIRS.mat';
vout.src_output = substruct('.','NIRSmat');
vout.tgt_spec   = cfg_findspec({{'filter','mat','strtype','e'}});