function liom_contrast = nirs_run_liom_contrast_cfg


NIRSmat         = cfg_files; %Select NIRS.mat for this subject
NIRSmat.name    = 'NIRS.mat'; % The displayed name
NIRSmat.tag     = 'NIRSmat';       %file names
NIRSmat.filter  = 'mat';
NIRSmat.ufilter = '^NIRS.mat$';
NIRSmat.num     = [1 Inf];     % Number of inputs required
NIRSmat.help    = {'Select NIRS.mat for the subject(s).'}; % help text displayed

DelPreviousData      = cfg_menu;
DelPreviousData.tag  = 'DelPreviousData';
DelPreviousData.name = 'Delete Previous data file';
DelPreviousData.labels = {'True','False'};
DelPreviousData.values = {1,0};
DelPreviousData.val  = {0};
DelPreviousData.help = {'Delete the previous data file.'}';

CreateNIRSCopy_false         = cfg_branch;
CreateNIRSCopy_false.tag     = 'CreateNIRSCopy_false';
CreateNIRSCopy_false.name    = 'Do not copy NIRS structure';
CreateNIRSCopy_false.help    = {'Do not copy NIRS structure.'
    'This will write over the previous NIRS.mat'}';

NewNIRSdir         = cfg_entry;
NewNIRSdir.name    = 'Directory for NIRS.mat';
NewNIRSdir.tag     = 'NewNIRSdir';
NewNIRSdir.strtype = 's';
NewNIRSdir.val{1}    = 'NewDir';
NewNIRSdir.num     = [1 Inf];
NewNIRSdir.help    = {'Directory for NIRS.mat.'}';

CreateNIRSCopy         = cfg_branch;
CreateNIRSCopy.tag     = 'CreateNIRSCopy';
CreateNIRSCopy.name    = 'Create new directory and copy NIRS structure';
CreateNIRSCopy.val     = {NewNIRSdir};
CreateNIRSCopy.help    = {'Create new directory and copy NIRS structure there.'}';

%Common to most modules: for creating a new directory and copying NIRS.mat
NewDirCopyNIRS           = cfg_choice;
NewDirCopyNIRS.name      = 'Create new directory and copy NIRS.mat';
NewDirCopyNIRS.tag       = 'NewDirCopyNIRS';
NewDirCopyNIRS.values    = {CreateNIRSCopy_false CreateNIRSCopy};
NewDirCopyNIRS.val       = {CreateNIRSCopy_false};
NewDirCopyNIRS.help      = {'Choose whether to overwrite the NIRS.mat structure'
    'or to create a new directory'
    'and copy the NIRS.mat structure there'}';


%Select view
view         = cfg_entry;
view.name    = 'View';
view.tag     = 'view';
view.strtype = 'r';
view.num     = [1 Inf];
view.val     = {5};
view.help    = {['Enter view.  ',...
    '1: ventral  ',...
    '2: dorsal  ',...
    '3: right  ',...
    '4: left  ',...
    '5: frontal  ',...
    '6: occipital']}; % help text displayed


% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % NIRS_SPM Contrast calculations
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%File for channel coregistration 'preproc_info' generated by NIRS_SPM
NIRS_SPM_Coregistration_Channels         = cfg_files;
NIRS_SPM_Coregistration_Channels.name    = 'Select file of coregistration info';
NIRS_SPM_Coregistration_Channels.tag     = 'NIRS_SPM_Coregistration_Channels';
NIRS_SPM_Coregistration_Channels.filter  = 'mat';
NIRS_SPM_Coregistration_Channels.num     = [1 1];
NIRS_SPM_Coregistration_Channels.help    = {'Select file of channel '
    'coregistration ''preproc_info'' generated by NIRS_SPM.'}';

%
%Contrast name
contrast_name         = cfg_entry;
contrast_name.name    = 'Contrast name';
contrast_name.tag     = 'contrast_name';
contrast_name.strtype = 's';
contrast_name.num     = [1 Inf];
contrast_name.help    = {'Contrast name'};

%Contrast vector
contrast_c         = cfg_entry;
contrast_c.name    = 'Contrast vector';
contrast_c.tag     = 'contrast_c';
contrast_c.strtype = 'r';
contrast_c.num     = [1 Inf];
contrast_c.help    = {'Contrast vector'};

contrast_data         = cfg_branch;
contrast_data.tag     = 'contrast_data';
contrast_data.name    = 'Contrasts';
contrast_data.val     = {contrast_name contrast_c}; %contrast_type
contrast_data.help    = {'Specify contrasts.'};
%
% contrast_struct         = cfg_repeat;
% contrast_struct.tag     = 'contrast_struct';
% contrast_struct.name    = 'Contrasts';
% contrast_struct.help    = {'Specify contrasts'};
% contrast_struct.values  = {contrast_data};
% contrast_struct.num     = [1 Inf];
%
% % Executable Branch
% NIRS_SPM_contrast      = cfg_exbranch;
% NIRS_SPM_contrast.name = 'NIRS_SPM Contrast Calculations';
% NIRS_SPM_contrast.tag  = 'NIRS_SPM_contrast';
% NIRS_SPM_contrast.val  = {Dmx_files NIRS_SPM_Coregistration_Channels ...
%                 view contrast_struct};
% NIRS_SPM_contrast.prog = @nirs_run_NIRS_SPM_contrast;
% NIRS_SPM_contrast.vout = @nirs_cfg_vout_NIRS_SPM_contrast;
% NIRS_SPM_contrast.help = {'NIRS_SPM Contrast Calculations.'};
%
% function vout = nirs_cfg_vout_NIRS_SPM_contrast(job)
% vout = cfg_dep;
% vout.sname      = 'NIRS.mat';
% vout.src_output = substruct('.','NIRSmat');
% vout.tgt_spec   = cfg_findspec({{'filter','mat','strtype','e'}});
% end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Liom Contrast calculations - based on tube formula and code by NIRS_SPM
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% liom_contrast_struct         = cfg_repeat;
% liom_contrast_struct.tag     = 'liom_contrast_struct';
% liom_contrast_struct.name    = 'Contrasts';
% liom_contrast_struct.help    = {'Specify contrasts'
%     'NOTE: this is an older method to specify contrasts, which will disappear.'}';
% liom_contrast_struct.values  = {contrast_data};
% liom_contrast_struct.num     = [0 Inf];

contrast_p_value         = cfg_entry;
contrast_p_value.name    = 'Contrast uncorrected p_value';
contrast_p_value.tag     = 'contrast_p_value';
contrast_p_value.strtype = 'r';
contrast_p_value.num     = [1 1];
contrast_p_value.val     = {0.05};
contrast_p_value.help    = {'Contrast uncorrected p_value'};

spatial_LPF_radius         = cfg_entry;
spatial_LPF_radius.name    = 'Spatial LPF radius';
spatial_LPF_radius.tag     = 'spatial_LPF_radius';
spatial_LPF_radius.strtype = 'r';
spatial_LPF_radius.num     = [1 1];
spatial_LPF_radius.val     = {3};
spatial_LPF_radius.help    = {'Enter radius of spatial low pass filter in pixels.'
    'One pixel is very approximately 1 mm. FWHM will be twice this radius.'
    'If 0 is entered, this is equivalent to no spatial filtering.'
    'Spatial filtering will be applied linearly even though '
    'stereographic projection is nonlinear.'}';

spatial_LPF_On         = cfg_branch;
spatial_LPF_On.tag     = 'spatial_LPF_On';
spatial_LPF_On.name    = 'Spatial LP filter';
spatial_LPF_On.val     = {spatial_LPF_radius};
spatial_LPF_On.help    = {'Spatial low-pass filter.'};

spatial_LPF_Off         = cfg_branch;
spatial_LPF_Off.tag     = 'spatial_LPF_Off';
spatial_LPF_Off.name    = 'Spatial filter off';
spatial_LPF_Off.val     = {};
spatial_LPF_Off.help    = {'Spatial low pass filter turned off.'};

spatial_LPF      = cfg_choice;
spatial_LPF.tag  = 'spatial_LPF';
spatial_LPF.name = 'Spatial Low Pass Filter';
spatial_LPF.values = {spatial_LPF_On spatial_LPF_Off};
spatial_LPF.val = {spatial_LPF_Off};
spatial_LPF.help = {'Choose whether to include a spatial Low Pass Filter'
    'on the interpolated estimates and their variance before constructing'
    'statistical maps.'}';

contrast_figures      = cfg_menu;
contrast_figures.tag  = 'contrast_figures';
contrast_figures.name = 'Generate figures';
contrast_figures.labels = {'No','Both .fig and .tiff','Only .fig','Only .tiff'};
contrast_figures.values = {0,1,2,3};
contrast_figures.val = {3};
contrast_figures.help = {'Generate contrast figures. '
    'Note .fig colorbar is incorrect - it is not saved properly by Matlab.'
    'Use .tiff to view colorbar for t-stat.'}';

figures_visible      = cfg_menu;
figures_visible.tag  = 'figures_visible';
figures_visible.name = 'Make figures visible';
figures_visible.labels = {'Yes','No'};
figures_visible.values = {1,0};
figures_visible.val = {0};
figures_visible.help = {'Make figures visible during processing.'}';

colorbar_max         = cfg_entry;
colorbar_max.name    = 'Colorbar maximum value';
colorbar_max.tag     = 'colorbar_max';
colorbar_max.strtype = 'r';
colorbar_max.num     = [1 1];
colorbar_max.val     = {5};
colorbar_max.help    = {'Enter maximum value for colorbar'};

colorbar_min         = cfg_entry;
colorbar_min.name    = 'Colorbar minimum value';
colorbar_min.tag     = 'colorbar_min';
colorbar_min.strtype = 'r';
colorbar_min.num     = [1 1];
colorbar_min.val     = {2};
colorbar_min.help    = {'Enter minimum value for colorbar'};


colorbar_max2         = cfg_entry;
colorbar_max2.name    = 'Colorbar maximum value';
colorbar_max2.tag     = 'colorbar_max2';
colorbar_max2.strtype = 'r';
colorbar_max2.num     = [1 1];
colorbar_max2.val     = {-2};
colorbar_max2.help    = {'Enter maximum value for colorbar for negative maps'};

colorbar_min2         = cfg_entry;
colorbar_min2.name    = 'Colorbar minimum value';
colorbar_min2.tag     = 'colorbar_min2';
colorbar_min2.strtype = 'r';
colorbar_min2.num     = [1 1];
colorbar_min2.val     = {-5};
colorbar_min2.help    = {'Enter minimum value for colorbar for negative maps'};

colorbar_override      = cfg_branch;
colorbar_override.name      = 'Override colorbar';
colorbar_override.tag       = 'colorbar_override';
colorbar_override.val       = {colorbar_min colorbar_max colorbar_min2 colorbar_max2};
colorbar_override.help      = {'Override colorbar.'};

colorbar_default      = cfg_branch;
colorbar_default.name      = 'Default colorbar';
colorbar_default.tag       = 'colorbar_default';
colorbar_default.val       = {};
colorbar_default.help      = {'Default colorbar.'};

override_colorbar           = cfg_choice;
override_colorbar.name      = 'Override colorbar';
override_colorbar.tag       = 'override_colorbar';
override_colorbar.values    = {colorbar_default colorbar_override};
override_colorbar.val       = {colorbar_default};
override_colorbar.help      = {'Override default treatment of colorbar.'
    'User can then specify maximum and minimum values for the colorbar.'}';

GenerateInverted      = cfg_menu;
GenerateInverted.tag  = 'GenerateInverted';
GenerateInverted.name = 'Generate Inverted Responses';
GenerateInverted.labels = {'Yes','No'};
GenerateInverted.values = {1,0};
GenerateInverted.val = {1};
GenerateInverted.help = {'Generate contrasts for inverted responses.'};

GroupColorbars      = cfg_menu;
GroupColorbars.tag  = 'GroupColorbars';
GroupColorbars.name = 'Group or separate colorbars';
GroupColorbars.labels = {'Group','Separate'};
GroupColorbars.values = {1,0};
GroupColorbars.val = {0};
GroupColorbars.help = {'When considering deactivations (inverted responses),'
    'This allows displaying one (group) or two (separate) colorbars'}';

SmallFigures      = cfg_menu;
SmallFigures.tag  = 'SmallFigures';
SmallFigures.name = 'Large or small figures';
SmallFigures.labels = {'Large','Small'};
SmallFigures.values = {0,1};
SmallFigures.val = {1};
SmallFigures.help = {'Write to disk large or small (compressed) figures.'}';

ProcessContrastsBySession      = cfg_menu;
ProcessContrastsBySession.tag  = 'ProcessContrastsBySession';
ProcessContrastsBySession.name = 'Process Contrasts By Session';
ProcessContrastsBySession.labels = {'Yes','No','Both'};
ProcessContrastsBySession.values = {1,0,2};
ProcessContrastsBySession.val = {1};
ProcessContrastsBySession.help = {'Important option, careful; only applies'
    'when there are two or more sessions'
    'if yes, contrasts defined over more than one session will be ignored'
    'if no, contrasts defined over only one session will be processed as'
    'a contrast defined over the full design matrix over all sessions, with'
    'statistics, e.g. number of degrees of freedom, calculated for the full design matrix.'
    'if both, both options will be run.'}';

GroupMultiSession           = cfg_menu;
GroupMultiSession.name      = 'Group Multi-Session';
GroupMultiSession.tag       = 'GroupMultiSession';
GroupMultiSession.labels    = {'Yes' 'No'};
GroupMultiSession.values    = {1,0};
GroupMultiSession.val       = {0};
GroupMultiSession.help      = {'Group Multi Session'
    'If selected, with option ProcessContrastBySession set to 0,'
    'Contrasts defined as vectors over all sessions will be treated.'}';

% Study_type           = cfg_menu;
% Study_type.name      = 'Study type';
% Study_type.tag       = 'Study_type';
% Study_type.labels    = {'Group Single Session' 'Group Multi Sessions' 'Single Subject Multi Sessions'};
% Study_type.values    = {2,1,0};
% Study_type.val       = {2};
% Study_type.help      = {'Study type: note that all cases can be used for one or more subjects.'
%     'However, the treatment by liom_contrast and/or liom_group will be affected by this choice'
%     'Group Single Session: use when there is only one session, or with more than one session but contrasts do not combine different sessions'
%     'Group Multi Sessions: use when contrasts are combined over more than one session'
%     'Single Subject Multi Sessions: use when subjects will not be combined into a group analysis.'}';

GroupFiguresIntoSubplots      = cfg_menu;
GroupFiguresIntoSubplots.tag  = 'GroupFiguresIntoSubplots';
GroupFiguresIntoSubplots.name = 'Group Figures Into Subplots';
GroupFiguresIntoSubplots.labels = {'Yes','No'};
GroupFiguresIntoSubplots.values = {1,0};
GroupFiguresIntoSubplots.val = {1};
GroupFiguresIntoSubplots.help = {'Group Figures Into Subplots.'};


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% From spm spm_cfg_con
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% ---------------------------------------------------------------------
% name Name
% ---------------------------------------------------------------------
name         = cfg_entry;
name.tag     = 'name';
name.name    = 'Name';
name.help    = {'Name of contrast'};
name.strtype = 's';
name.num     = [1 Inf];
% ---------------------------------------------------------------------
% convec T contrast vector
% ---------------------------------------------------------------------
convec         = cfg_entry;
convec.tag     = 'convec';
convec.name    = 'T contrast vector';
convec.help    = {'Enter T contrast vector. This is done similarly to the contrast manager. A 1 x n vector should be entered for T-contrasts.'};
convec.strtype = 'e';
convec.num     = [1 Inf];
% ---------------------------------------------------------------------
% sessrep Replicate over sessions
% ---------------------------------------------------------------------
sessrep         = cfg_menu;
sessrep.tag     = 'sessrep';
sessrep.name    = 'Replicate over sessions';
sessrep.val = {'none'};
sessrep.help    = {
    'If there are multiple sessions with identical conditions, one might want to specify contrasts which are identical over sessions. This can be done automatically based on the contrast spec for one session.'
    'Contrasts can be either replicated (thus testing average effects over sessions) or created per session. In both cases, zero padding up to the length of each session and the block effects is done automatically. In addition, weights of replicated contrasts can be scaled by the number of sessions. This allows to use the same contrast manager batch for fMRI analyses with a variable number of sessions. The scaled contrasts can then be compared in a 2nd level model without a need for further adjustment of effect sizes.'
    }';
sessrep.labels = {
    'Don''t replicate'
    'Replicate'
    'Replicate&Scale'
    'Create per session'
    'Both: Replicate + Create per session'
    'Both: Replicate&Scale + Create per session'
    }';
sessrep.values = {
    'none'
    'repl'
    'replsc'
    'sess'
    'both'
    'bothsc'
    }';
% ---------------------------------------------------------------------
% tcon T-contrast
% ---------------------------------------------------------------------
tcon         = cfg_branch;
tcon.tag     = 'tcon';
tcon.name    = 'T-contrast';
tcon.val     = {name convec sessrep };
tcon.help    = {
    '* Simple one-dimensional contrasts for an SPM{T}'
    ''
    'A simple contrast for an SPM{T} tests the null hypothesis c''B=0 against the one-sided alternative c''B>0, where c is a column vector. '
    ''
    '    Note that throughout SPM, the transpose of the contrast weights is used for display and input. That is, you''ll enter and visualise c''. For an SPM{T} this will be a row vector.'
    ''
    'For example, if you have a design in which the first two columns of the design matrix correspond to the effects for "baseline" and "active" conditions respectively, then a contrast with weights c''=[-1,+1,0,...] (with zero weights for any other parameters) tests the hypothesis that there is no "activation" (the parameters for both conditions are the same), against the alternative that there is some activation (i.e. the parameter for the "active" condition is greater than that for the "baseline" condition). The resulting SPM{T} (created by spm_getSPM.m) is a statistic image, with voxel values the value of the t-statistic for the specified contrast at that location. Areas of the SPM{T} with high voxel values indicate evidence for "activation". To look for areas of relative "de-activation", the inverse contrast could be used c''=[+1,-1,0,...].'
    ''
    'Similarly, if you have a design where the third column in the design matrix is a covariate, then the corresponding parameter is essentially a regression slope, and a contrast with weights c''=[0,0,1,0,...] (with zero weights for all parameters but the third) tests the hypothesis of zero regression slope, against the alternative of a positive slope. This is equivalent to a test no correlation, against the alternative of positive correlation. If there are other terms in the model beyond a constant term and the covariate, then this correlation is apartial correlation, the correlation between the data Y and the covariate, after accounting for the other effects.'
    }';
% ---------------------------------------------------------------------
% name Name
% ---------------------------------------------------------------------
name         = cfg_entry;
name.tag     = 'name';
name.name    = 'Name';
name.help    = {'Name of contrast'};
name.strtype = 's';
name.num     = [1 Inf];
% ---------------------------------------------------------------------
% convec F contrast vector
% ---------------------------------------------------------------------
convec         = cfg_entry;
convec.tag     = 'convec';
convec.name    = 'F contrast vector';
convec.help    = {'Enter F contrast vector. This is done similarly to the contrast manager. One or multiline contrasts may be entered.'};
convec.strtype = 'e';
convec.num     = [Inf Inf];
% ---------------------------------------------------------------------
% generic Contrast vectors
% ---------------------------------------------------------------------
generic         = cfg_repeat;
generic.tag     = 'generic';
generic.name    = 'Contrast vectors';
generic.help    = {'F contrasts are defined by a series of vectors.'};
generic.values  = {convec };
generic.num     = [1 Inf];
% ---------------------------------------------------------------------
% sessrep Replicate over sessions
% ---------------------------------------------------------------------
sessrep         = cfg_menu;
sessrep.tag     = 'sessrep';
sessrep.name    = 'Replicate over sessions';
sessrep.val = {'none'};
sessrep.help    = {
    'If there are multiple sessions with identical conditions, one might want to specify contrasts which are identical over sessions. This can be done automatically based on the contrast spec for one session.'
    'Contrasts can be either replicated (either testing average effects over sessions or per-session/condition effects) or created per session. In both cases, zero padding up to the length of each session and the block effects is done automatically.'
    }';
sessrep.labels = {
    'Don''t replicate'
    'Replicate (average over sessions)'
    'Replicate (no averaging)'
    'Create per session'
    'Both - ''Per session'' and ''Replicate (average over sessions)'''
    }';
sessrep.values = {
    'none'
    'repl'
    'replna'
    'sess'
    'both'
    }';
% ---------------------------------------------------------------------
% fcon F-contrast
% ---------------------------------------------------------------------
fcon         = cfg_branch;
fcon.tag     = 'fcon';
fcon.name    = 'F-contrast';
fcon.val     = {name generic sessrep };
fcon.help    = {
    '* Linear constraining matrices for an SPM{F}'
    ''
    'The null hypothesis c''B=0 can be thought of as a (linear) constraint on the full model under consideration, yielding a reduced model. Taken from the viewpoint of two designs, with the full model an extension of the reduced model, the null hypothesis is that the additional terms in the full model are redundent.'
    ''
    'Statistical inference proceeds by comparing the additional variance explained by full design over and above the reduced design to the error variance (of the full design), an "Extra Sum-of-Squares" approach yielding an F-statistic for each voxel, whence an SPM{F}.'
    ''
    'This is useful in a number of situations:'
    ''
    '* Two sided tests'
    ''
    'The simplest use of F-contrasts is to effect a two-sided test of a simple linear contrast c''B, where c is a column vector. The SPM{F} is the square of the corresponding SPM{T}. High values of the SPM{F} therefore indicate evidence against the null hypothesis c''B=0 in favour of the two-sided alternative c''B~=0.'
    ''
    '* General linear hypotheses'
    ''
    'Where the contrast weights is a matrix, the rows of the (transposed) contrast weights matrix c'' must define contrasts in their own right, and the test is effectively simultaneously testing the null hypotheses associated with the individual component contrasts with weights defined in the rows. The null hypothesis is still c''B=0, but since c is a matrix, 0 here is a zero vector rather than a scalar zero, asserting that under the null hypothesis all the component hypotheses are true.'
    ''
    'For example: Suppose you have a language study with 3 word categories (A,B & C), and would like to test whether there is any difference at all between the three levels of the "word category" factor.'
    ''
    'The design matrix might look something like:'
    ''
    '         [ 1 0 0 ..]'
    '         [ : : : ..]'
    '         [ 1 0 0 ..]'
    '         [ 0 1 0 ..]'
    '    X =  [ : : : ..]'
    '         [ 0 1 0 ..]'
    '         [ 0 0 1 ..]'
    '         [ : : : ..]'
    '         [ 0 0 1 ..]'
    '         [ 0 0 0 ..]'
    '         [ : : : ..]'
    ''
    ' ...with the three levels of the "word category" factor modelled in the  first three columns of the design matrix.'
    ''
    'The matrix of contrast weights will look like:'
    ''
    ' c'' = [1 -1  0 ...;'
    '       0  1 -1 ...]'
    ''
    'Reading the contrasts weights in each row of c'', we see that row 1 states that category A elicits the same response as category B, row 2 that category B elicits the same response as category C, and hence together than categories A, B & C all elicit the same response.'
    ''
    'The alternative hypothesis is simply that the three levels are not all the same, i.e. that there is some difference in the paraeters for the three levels of the factor: The first and the second categories produce different brain responses, OR the second and third categories, or both.'
    ''
    'In other words, under the null hypothesis (the categories produce the same brain responses), the model reduces to one in which the three level "word category" factor can be replaced by a single "word" effect, since there is no difference in the parameters for each category. The corresponding design matrix would have the first three columns replaced by a single column that is the sum (across rows) of the first three columns in the design matric above, modelling the brain response to a word, whatever is the category. The F-contrast above is in fact testing the hypothesis that this reduced design doesn''t account for significantly less variance than the full design with an effect for each word category.'
    ''
    'Another way of seeing that, is to consider a reparameterisation of the model, where the first column models effects common to all three categories, with the second and third columns modelling the differences between the three conditions, for example:'
    ''
    '         [ 1  1  0 ..]'
    '         [ :  :  : ..]'
    '         [ 1  1  0 ..]'
    '         [ 1  0  1 ..]'
    '    X =  [ :  :  : ..]'
    '         [ 1  0  1 ..]'
    '         [ 1 -1 -1 ..]'
    '         [ :  :  : ..]'
    '         [ 1 -1 -1 ..]'
    '         [ 0  0  0 ..]'
    '         [ :  :  : ..]'
    ''
    'In this case, an equivalent F contrast is of the form'
    ' c'' = [ 0 1 0 ...;'
    '        0 0 1 ...]'
    'and would be exactly equivalent to the previous contrast applied to the previous design. In this latter formulation, you are asking whewher the two columns modelling the "interaction space" account for a significant amount of variation (variance) of the data. Here the component contrasts in the rows of c'' are simply specifying that the parameters for the corresponding rows are are zero, and it is clear that the F-test is comparing this full model with a reduced model in which the second and third columns of X are omitted.'
    ''
    '    Note the difference between the following two F-contrasts:'
    '         c'' = [ 0 1 0 ...;     (1)'
    '                0 0 1 ...]'
    '     and'
    '         c'' = [ 0 1 1 ...]     (2)'
    ''
    '    The first is an F-contrast, testing whether either of the parameters for the effects modelled in the 2nd & 3rd columns of the design matrix are significantly different from zero. Under the null hypothesis c''B=0, the first contrast imposes a two-dimensional constraint on the design. The second contrast tests whether the SUM of the parameters for the 2nd & 3rd columns is significantly different from zero. Under the null hypothesis c''B=0, this second contrast only imposes a one dimensional constraint on the design.'
    ''
    '    An example of the difference between the two is that the first contrast would be sensitive to the situation where the 2nd & 3rd parameters were +a and -a, for some constant a, wheras the second contrast would not detect this, since the parameters sum to zero.'
    ''
    'The test for an effect of the factor "word category" is an F-test with 3-1=2 "dimensions", or degrees of freedom.'
    ''
    '* Testing the significance of effects modelled by multiple columns'
    ''
    'A conceptially similar situation arises when one wonders whether a set of coufound effects are explaining any variance in the data. One important advantage of testing the with F contrasts rather than one by one using SPM{T}''s is the following. Say you have two covariates that you would like to know whether they can "predict" the brain responses, and these two are correlated (even a small correlation would be important in this instance). Testing one and then the other may lead you to conclude that there is no effect. However, testing with an F test the two covariates may very well show a not suspected effect. This is because by testing one covariate after the other, one never tests for what is COMMON to these covariates (see Andrade et al, Ambiguous results in functional neuroimaging, NeuroImage, 1999).'
    ''
    ''
    'More generally, F-tests reflect the usual analysis of variance, while t-tests are traditionally post hoc tests, useful to see in which direction is an effect going (positive or negative). The introduction of F-tests can also be viewed as a first means to do model selection.'
    ''
    ''
    'Technically speaking, an F-contrast defines a number of directions (as many as the rank of the contrast) in the space spanned by the column vectors of the design matrix. These directions are simply given by X*c if the vectors of X are orthogonal, if not, the space define by c is a bit more complex and takes care of the correlation within the design matrix. In essence, an F-contrast is defining a reduced model by imposing some linear constraints (that have to be estimable, see below) on the parameters estimates. Sometimes, this reduced model is simply made of a subset of the column of the original design matrix but generally, it is defined by a combination of those columns. (see spm_FcUtil for what (I hope) is an efficient handling of F-contrats computation).'
    }';
% ---------------------------------------------------------------------
% name Name
% ---------------------------------------------------------------------
name         = cfg_entry;
name.tag     = 'name';
name.name    = 'Name';
name.help    = {'Name of contrast'};
name.strtype = 's';
name.num     = [1 Inf];
% ---------------------------------------------------------------------
% conweight Contrast weight
% ---------------------------------------------------------------------
conweight         = cfg_entry;
conweight.tag     = 'conweight';
conweight.name    = 'Contrast weight';
conweight.help    = {'The contrast weight for the selected column.'};
conweight.strtype = 'e';
conweight.num     = [1 1];
% ---------------------------------------------------------------------
% colcond Condition #
% ---------------------------------------------------------------------
colcond         = cfg_entry;
colcond.tag     = 'colcond';
colcond.name    = 'Condition #';
colcond.help    = {'Select which condition function set is to be contrasted.'};
colcond.strtype = 'e';
colcond.num     = [1 1];
% ---------------------------------------------------------------------
% colbf Basis function #
% ---------------------------------------------------------------------
colbf         = cfg_entry;
colbf.tag     = 'colbf';
colbf.name    = 'Basis function #';
colbf.help    = {'Select which basis function from the basis function set is to be contrasted.'};
colbf.strtype = 'e';
colbf.num     = [1 1];
% ---------------------------------------------------------------------
% colmod Parametric modulation #
% ---------------------------------------------------------------------
colmod         = cfg_entry;
colmod.tag     = 'colmod';
colmod.name    = 'Parametric modulation #';
colmod.help    = {'Select which parametric modulation is to be contrasted. If there is no time/parametric modulation, enter "1". If there are both time and parametric modulations, then time modulation comes before parametric modulation.'};
colmod.strtype = 'e';
colmod.num     = [1 1];
% ---------------------------------------------------------------------
% colmodord Parametric modulation order
% ---------------------------------------------------------------------
colmodord         = cfg_entry;
colmodord.tag     = 'colmodord';
colmodord.name    = 'Parametric modulation order';
colmodord.help    = {
    'Order of parametric modulation to be contrasted. '
    ''
    '0 - the basis function itself, 1 - 1st order mod etc'
    }';
colmodord.strtype = 'e';
colmodord.num     = [1 1];
% ---------------------------------------------------------------------
% colconds Contrast entry
% ---------------------------------------------------------------------
colconds         = cfg_branch;
colconds.tag     = 'colconds';
colconds.name    = 'Contrast entry';
colconds.val     = {conweight colcond colbf colmod colmodord };
colconds.help    = {''};
% ---------------------------------------------------------------------
% generic T contrast for conditions
% ---------------------------------------------------------------------
generic         = cfg_repeat;
generic.tag     = 'generic';
generic.name    = 'T contrast for conditions';
generic.help    = {'Assemble your contrast column by column.'};
generic.values  = {colconds };
generic.num     = [1 Inf];
% ---------------------------------------------------------------------
% colreg T contrast for extra regressors
% ---------------------------------------------------------------------
colreg         = cfg_entry;
colreg.tag     = 'colreg';
colreg.name    = 'T contrast for extra regressors';
colreg.help    = {'Enter T contrast vector for extra regressors.'};
colreg.strtype = 'e';
colreg.num     = [1 Inf];
% ---------------------------------------------------------------------
% coltype Contrast columns
% ---------------------------------------------------------------------
coltype         = cfg_choice;
coltype.tag     = 'coltype';
coltype.name    = 'Contrast columns';
coltype.val     = {generic };
coltype.help    = {'Contrasts can be specified either over conditions or over extra regressors.'};
coltype.values  = {generic colreg };
% ---------------------------------------------------------------------
% sessions Session(s)
% ---------------------------------------------------------------------
sessions         = cfg_entry;
sessions.tag     = 'sessions';
sessions.name    = 'Session(s)';
sessions.help    = {'Enter session number(s) for which this contrast should be created. If more than one session number is specified, the contrast will be an average contrast over the specified conditions or regressors from these sessions.'};
sessions.strtype = 'e';
sessions.num     = [1 Inf];
% ---------------------------------------------------------------------
% tconsess T-contrast (cond/sess based)
% ---------------------------------------------------------------------
tconsess         = cfg_branch;
tconsess.tag     = 'tconsess';
tconsess.name    = 'T-contrast (cond/sess based)';
tconsess.val     = {name coltype sessions };
tconsess.help    = {
    'Define a contrast in terms of conditions or regressors instead of columns of the design matrix. This allows to create contrasts automatically even if some columns are not always present (e.g. parametric modulations).'
    ''
    'Each contrast column can be addressed by specifying'
    '* session number'
    '* condition number'
    '* basis function number'
    '* parametric modulation number and'
    '* parametric modulation order.'
    ''
    'If the design is specified without time or parametric modulation, SPM creates a "pseudo-modulation" with order zero. To put a contrast weight on a basis function one therefore has to enter "1" for parametric modulation number and "0" for parametric modulation order.'
    ''
    'Time and parametric modulations are not distinguished internally. If time modulation is present, it will be parametric modulation "1", and additional parametric modulations will be numbered starting with "2".'
    ''
    '* Simple one-dimensional contrasts for an SPM{T}'
    ''
    'A simple contrast for an SPM{T} tests the null hypothesis c''B=0 against the one-sided alternative c''B>0, where c is a column vector. '
    ''
    '    Note that throughout SPM, the transpose of the contrast weights is used for display and input. That is, you''ll enter and visualise c''. For an SPM{T} this will be a row vector.'
    ''
    'For example, if you have a design in which the first two columns of the design matrix correspond to the effects for "baseline" and "active" conditions respectively, then a contrast with weights c''=[-1,+1,0,...] (with zero weights for any other parameters) tests the hypothesis that there is no "activation" (the parameters for both conditions are the same), against the alternative that there is some activation (i.e. the parameter for the "active" condition is greater than that for the "baseline" condition). The resulting SPM{T} (created by spm_getSPM.m) is a statistic image, with voxel values the value of the t-statistic for the specified contrast at that location. Areas of the SPM{T} with high voxel values indicate evidence for "activation". To look for areas of relative "de-activation", the inverse contrast could be used c''=[+1,-1,0,...].'
    ''
    'Similarly, if you have a design where the third column in the design matrix is a covariate, then the corresponding parameter is essentially a regression slope, and a contrast with weights c''=[0,0,1,0,...] (with zero weights for all parameters but the third) tests the hypothesis of zero regression slope, against the alternative of a positive slope. This is equivalent to a test no correlation, against the alternative of positive correlation. If there are other terms in the model beyond a constant term and the covariate, then this correlation is apartial correlation, the correlation between the data Y and the covariate, after accounting for the other effects.'
    }';
% ---------------------------------------------------------------------
% consess Contrast Sessions
% ---------------------------------------------------------------------
consess         = cfg_repeat;
consess.tag     = 'consess';
consess.name    = 'Contrast Sessions';
consess.help    = { ' NOTE: IF ONLY BASIC CONTRASTS ARE REQUIRED,'
    ' No need to specify any contrasts -- they will be generated automatically.'
    ' If more contrasts are required, all need to be specified.'
    ' '
    'For general linear model Y = XB + E with data Y, desgin matrix X, parameter vector B, and (independent) errors E, a contrast is a linear combination of the parameters c''B. Usually c is a column vector, defining a simple contrast of the parameters, assessed via an SPM{T}. More generally, c can be a matrix (a linear constraining matrix), defining an "F-contrast" assessed via an SPM{F}.'
    ''
    'The vector/matrix c contains the contrast weights. It is this contrast weights vector/matrix that must be specified to define the contrast. The null hypothesis is that the linear combination c''B is zero. The order of the parameters in the parameter (column) vector B, and hence the order to which parameters are referenced in the contrast weights vector c, is determined by the construction of the design matrix.'
    ''
    'There are two types of contrast in SPM: simple contrasts for SPM{T}, and "F-contrasts" for SPM{F}.'
    ''
    'For a thorough theoretical treatment, see the Human Brain Function book and the statistical literature referenced therein.'
    ''
    ''
    '* Non-orthogonal designs'
    ''
    'Note that parameters zero-weighted in the contrast are still included in the model. This is particularly important if the design is not orthogonal (i.e. the columns of the design matrix are not orthogonal). In effect, the significance of the contrast is assessed *after* accounting for the other effects in the design matrix. Thus, if two covariates are correlated, testing the significance of the parameter associated with one will only test for the part that is not present in the second covariate. This is a general point that is also true for F-contrasts. See Andrade et al, Ambiguous results in functional neuroimaging, NeuroImage, 1999, for a full description of the effect of non othogonal design testing.'
    ''
    ''
    '* Estimability'
    ''
    'The contrast c''B is estimated by c''b, where b are the parameter estimates given by b=pinv(X)*Y.'
    ''
    'However, if a design is rank-deficient (i.e. the columns of the design matrix are not linearly independent), then the parameters are not unique, and not all linear combinations of the parameter are valid contrasts, since contrasts must be uniquely estimable.'
    ''
    'A weights vector defines a valid contrast if and only if it can be constructed as a linear combination of the rows of the design matrix. That is c'' (the transposed contrast vector - a row vector) is in the row-space of the design matrix.'
    ''
    'Usually, a valid contrast will have weights that sum to zero over the levels of a factor (such as condition).'
    ''
    'A simple example is a simple two condition design including a constant, with design matrix'
    ''
    '          [ 1 0 1 ]'
    '          [ : : : ]'
    '     X =  [ 1 0 1 ]'
    '          [ 0 1 1 ]'
    '          [ : : : ]'
    '          [ 0 1 1 ]'
    ''
    'The first column corresponds to condition 1, the second to condition 2, and the third to a constant (mean) term. Although there are three columns to the design matrix, the design only has two degrees of freedom, since any one column can be derived from the other two (for instance, the third column is the sum of the first two). There is no unique set of parameters for this model, since for any set of parameters adding a constant to the two condition effects and subtracting it from the constant effect yields another set of viable parameters. However, the difference between the two condition effects is uniquely estimated, so c''=[-1,+1,0] does define a contrast.'
    ''
    'If a parameter is estimable, then the weights vector with a single "1" corresponding to that parameter (and zero elsewhere) defines a valid contrast.'
    ''
    ''
    '* Multiple comparisons'
    ''
    'Note that SPM implements no corrections to account for you looking at multiple contrasts.'
    ''
    'If you are interested in a set of hypotheses that together define a consistent question, then you should account for this when assessing the individual contrasts. A simple Bonferroni approach would assess N simultaneous contrasts at significance level alpha/N, where alpha is the chosen significance level (usually 0.05).'
    ''
    'For two sided t-tests using SPM{T}s, the significance level should be halved. When considering both SPM{T}s produced by a contrast and it''s inverse (the contrast with negative weights), to effect a two-sided test to look for both "increases" and "decreases", you should review each SPM{T} at at level 0.05/2 rather than 0.05. (Or consider an F-contrast!)'
    ''
    ''
    '* Contrast images and ESS images'
    ''
    'For a simple contrast, SPM (spm_getSPM.m) writes a contrast image: con_????.{img,nii}, with voxel values c''b. (The ???? in the image names are replaced with the contrast number.) These contrast images (for appropriate contrasts) are suitable summary images of an effect at this level, and can be used as input at a higher level when effecting a random effects analysis. See spm_RandFX.man for further details.'
    ''
    'For an F-contrast, SPM (spm_getSPM.m) writes the Extra Sum-of-Squares (the difference in the residual sums of squares for the full and reduced model) as ess_????.{img,nii}. (Note that the ess_????.{img,nii} and SPM{T,F}_????.{img,nii} images are not suitable input for a higher level analysis.)'
    }';
consess.values  = {tcon fcon tconsess };
consess.num     = [0 Inf];

%%%%%%%%%%%%
% end - from spm_cfg_con
%%%%%%%%%%%
output_unc      = cfg_menu;
output_unc.tag  = 'output_unc';
output_unc.name = 'Output unc. figures';
output_unc.labels = {'Yes','No'};
output_unc.values = {1,0};
output_unc.val = {0};
output_unc.help = {'Output figures that are uncorrected against false positives.'}';

write_neg_pos      = cfg_menu;
write_neg_pos.tag  = 'write_neg_pos';
write_neg_pos.name = 'Write neg/pos separate contrasts';
write_neg_pos.labels = {'Yes', 'No'};
write_neg_pos.values = {1,0};
write_neg_pos.val    = {0};
write_neg_pos.help = {'If generating negative contrasts, whether to output '
    'separate maps for negative and positive contrasts and for both, '
    'or only the maps with both contrasts' }';

save_nifti_contrasts      = cfg_menu;
save_nifti_contrasts.tag  = 'save_nifti_contrasts';
save_nifti_contrasts.name = 'Save contrast images in nifti format';
save_nifti_contrasts.labels = {'Yes', 'No'};
save_nifti_contrasts.values = {1,0};
save_nifti_contrasts.val    = {0};
save_nifti_contrasts.help = {'This option is useful for 2nd level studies: '
    'It creates nifti images, one for each contrast, which can then be input'
    'Into an SPM 2nd level analysis.' }';

% contrast_dir_name        = cfg_entry;
% contrast_dir_name.name    = 'Name of folder to store the analysis';
% contrast_dir_name.tag     = 'contrast_dir_name';
% contrast_dir_name.strtype = 's';
% contrast_dir_name.num     = [1 Inf];
% contrast_dir_name.val{1}  = 'Contrast';
% contrast_dir_name.help    = {'Enter name of folder to store the analysis.'}';


NonlinearEpilepsyOn      = cfg_menu;
NonlinearEpilepsyOn.tag  = 'NonlinearEpilepsyOn';
NonlinearEpilepsyOn.name = 'Automated contrasts for nonlinearities in epilepsy';
NonlinearEpilepsyOn.labels = {'Yes', 'No'};
NonlinearEpilepsyOn.values = {1,0};
NonlinearEpilepsyOn.val    = {0};
NonlinearEpilepsyOn.help = {'This option is ONLY for '
    'Automated contrasts for nonlinearities in epilepsy'}';

TopoData        = cfg_files;
TopoData.tag    = 'TopoData';
TopoData.name   = 'TopoData';
TopoData.filter = '.mat';
TopoData.num    = [0 1];
TopoData.val{1} = {''};
TopoData.help   = {'Select TopoData if you want to run GLM. You can choose either the template or the one corresponding to your subject if it has already been calculated'};

% Executable Branch
liom_contrast      = cfg_exbranch;
liom_contrast.name = 'Liom Contrast Calculations';
liom_contrast.tag  = 'liom_contrast';
%PP removed: liom_contrast_struct
liom_contrast.val  = {NIRSmat NewDirCopyNIRS ProcessContrastsBySession GroupMultiSession view consess ...
    spatial_LPF GenerateInverted GroupColorbars contrast_p_value ...
    contrast_figures override_colorbar figures_visible GroupFiguresIntoSubplots ...
    output_unc SmallFigures write_neg_pos TopoData save_nifti_contrasts NonlinearEpilepsyOn}; %Study_type
liom_contrast.prog = @nirs_run_liom_contrast;
liom_contrast.vout = @nirs_cfg_vout_liom_contrast;
liom_contrast.help = {'Liom Contrast Calculations.'};

function vout = nirs_cfg_vout_liom_contrast(job)
vout = cfg_dep;
vout.sname      = 'NIRS.mat';
vout.src_output = substruct('.','NIRSmat');
vout.tgt_spec   = cfg_findspec({{'filter','mat','strtype','e'}});