function hdr = nirs_create_vol(fname, dim, dt, pinfo, mat, data)
hdr = struct('fname',fname,...
    'dim', dim,...
    'dt',   dt,...
    'pinfo',pinfo,...
    'mat',  mat);
hdr = spm_create_vol(hdr);
spm_write_vol(hdr, data);
end