function out = nirs_run_buildroi(varargin)
% GUI to build an ROI
% Create and initialise 'Build ROI' GUI for MonteCarlo Simulations
%_______________________________________________________________________
% Copyright (C) 2010 Laboratoire d'Imagerie Optique et Moleculaire

% Clément Bonnéry
% 2010-06

persistent PF FS WS roiwin   % GUI related constants
persistent handles

if (~strcmp(varargin{1},'initialise') &&...
        ~strcmp(varargin{1},'rf') &&...
        ~strcmp(varargin{1},'lb') &&...
        ~strcmp(varargin{1},'up') &&...
        ~strcmp(varargin{1},'lo') &&...
        ~strcmp(varargin{1},'br'))
    
    Action = 'welcome';
    P = varargin{1,1}.image_in{:};
    output_prefix = char(varargin{1,1}.output_prefix);
elseif strcmp(varargin{1},'initialise')
    Action = varargin{1};
    output_prefix = varargin{2};
elseif (strcmp(varargin{1},'rf') ||...
       strcmp(varargin{1},'lb') ||...
       strcmp(varargin{1},'up') ||...
       strcmp(varargin{1},'lo') ||...
       strcmp(varargin{1},'br'))
   Action = varargin{1};
end

switch lower(Action)
    
    case 'welcome'
        % Unless specified, set visibility to on
        if nargin==2
            if ~strcmp(varargin{2},'off') && ~strcmp(varargin{2},'Off')
                visibility = 'On';
            else
                visibility = 'Off';
            end
        else
            visibility = 'On';
        end
        
        % Get all default values (these may effect GUI)
        nirs_run_buildroi('initialise',output_prefix);
        
        % Since we are using persistent variables we better make sure
        % there is no-one else out there.
        if ~isempty(roiwin)
            figure(roiwin);
            set(roiwin,'Visible',visibility);
            return
        end
        
        S0   = spm('WinSize','0',1);
        WS   = spm('WinScale');
        FS   = spm('FontSizes');
        PF   = spm_platform('fonts');
        rect = [100 100 400 260].*WS;
        
        roiwin = figure('IntegerHandle','off',...
            'Name',sprintf('%s%s','MonteCarlo Simulation, Build ROI window',...
            spm('GetUser',' (%s)')),...
            'NumberTitle','off',...
            'Tag','FieldMap',...
            'Position',[S0(1),S0(2),0,0] + rect,...
            'Resize','off',...
            'Pointer','Arrow',...
            'Color',[1 1 1]*.8,...
            'MenuBar','none',...
            'DefaultTextFontName',PF.helvetica,...
            'DefaultTextFontSize',FS(10),...
            'DefaultUicontrolFontName',PF.helvetica,...
            'DefaultUicontrolFontSize',FS(10),...
            'HandleVisibility','on',...
            'Visible',visibility,...
            'DeleteFcn','FieldMap(''Quit'');');
        
        [dir,name,ext] = fileparts(P);
        Pname = fullfile([dir,'\',name,ext(1:4)]);
        spm_image('init',Pname);
        
        handles.V = spm_vol(P);
        handles.roi.b = handles.V.dim;
        
        % Frames and text
        uicontrol(roiwin,'Style','Frame','BackgroundColor',spm('Colour'),...
            'Position',[010 010 380 245].*WS);
        uicontrol(roiwin,'Style','Text','String','Build ROI',...
            'Position',[25 230 355 20].*WS,...
            'ForegroundColor','k','BackgroundColor',spm('Colour'),...
            'FontName',PF.times,'FontAngle','Italic')
        uicontrol(roiwin,'Style','Text','String','Set vertices',...
            'Position',[25 200 120 20].*WS,...
            'ForegroundColor','k','BackgroundColor',spm('Colour'),...
            'FontName',PF.times)
        
        % Vertice set button
        uicontrol(roiwin,'String','Set Right Front Vertice',...
            'Position',[25 170 120 22].*WS,...
            'ToolTipString','Push button to set the position (as many time you want and in the order you want)',...
            'CallBack','nirs_run_buildroi(''rf'');',...
            'Tag','button_rf');
        uicontrol(roiwin,'String','Set Left Back Vertice',...
            'Position',[25 140 120 22].*WS,...
            'ToolTipString','Push button to set the position (as many time you want and in the order you want)',...
            'CallBack','nirs_run_buildroi(''lb'');',...
            'Tag','button_lb');
        uicontrol(roiwin,'String','Set Up Vertice',...
            'Position',[25 110 120 22].*WS,...
            'ToolTipString','Push button to set the position (as many time you want and in the order you want)',...
            'CallBack','nirs_run_buildroi(''up'');',...
            'Tag','button_up');
        uicontrol(roiwin,'String','Set Low Vertice',...
            'Position',[25 80 120 22].*WS,...
            'ToolTipString','Push button to set the position (as many time you want and in the order you want)',...
            'CallBack','nirs_run_buildroi(''lo'');',...
            'Tag','button_lo');
        
        uicontrol(roiwin,'Style','Edit',...
            'Position',[155 170 120 22].*WS,...
            'ToolTipString','Right Front Vertice Position',...
            'CallBack','nirs_run_buildroi(''rf'');',...
            'Tag','pos_rf');
        uicontrol(roiwin,'Style','Edit',...
            'Position',[155 140 120 22].*WS,...
            'ToolTipString','Left Back Vertice Position',...
            'CallBack','nirs_run_buildroi(''lb'');',...
            'Tag','pos_lb');
        uicontrol(roiwin,'Style','Edit',...
            'Position',[155 110 120 22].*WS,...
            'ToolTipString','Up Vertice Position',...
            'CallBack','nirs_run_buildroi(''up'');',...
            'Tag','pos_up');
        uicontrol(roiwin,'Style','Edit',...
            'Position',[155 80 120 22].*WS,...
            'ToolTipString','Low Vertice Position',...
            'CallBack','nirs_run_buildroi(''lo'');',...
            'Tag','pos_lo');
        
        % Build ROI
%         if(sum(handles.ready2build)<4)
%             enable_build = 'Off';
%         else
%             enable_build = 'On';
%         end
            uicontrol(roiwin,'String','Build ROI',...
                'Position',[25 30 120 22].*WS,...
                'Enable','On',...
                'ToolTipString','Build ROI',...
                'CallBack','nirs_run_buildroi(''br'');',...
                'ForegroundColor','r',...
                'Tag','Build ROI');%enable_build,...
        
    case 'initialise'
        handles.roi=[];
        handles.roi.b=[];
        handles.V=[];
        handles.out_buildroi=[];
        handles.ready2build=zeros(4,1);
        handles.output_prefix = output_prefix;
    case 'rf'
        handles.roi.b = nirs_buildroi(handles.V,handles.roi.b,'getvertice','rf');
        h = findobj(get(roiwin,'Children'),'Tag','pos_rf');
        set(h,'String',strcat(int2str(handles.roi.b(2,3)),',',int2str(handles.roi.b(1,1))));
        handles.ready2build(1,1)=1;
    case 'up'
        handles.roi.b = nirs_buildroi(handles.V,handles.roi.b,'getvertice','up');
        h = findobj(get(roiwin,'Children'),'Tag','pos_up');
        set(h,'String',int2str(handles.roi.b(2,2)));
        handles.ready2build(2,1)=1;
    case 'lb'
        handles.roi.b = nirs_buildroi(handles.V,handles.roi.b,'getvertice','lb');
        h = findobj(get(roiwin,'Children'),'Tag','pos_lb');
        set(h,'String',strcat(int2str(handles.roi.b(2,1)),',',int2str(handles.roi.b(1,3))));
        handles.ready2build(3,1)=1;
    case 'lo'
        handles.roi.b = nirs_buildroi(handles.V,handles.roi.b,'getvertice','lo');
        h = findobj(get(roiwin,'Children'),'Tag','pos_lo');
        set(h,'String',int2str(handles.roi.b(1,2)));
        handles.ready2build(4,1)=1;
    case 'br'
        handles.out_buildroi = nirs_buildroi(handles.V,handles.roi.b,'build_ROI',handles.output_prefix);
        out = 1; %handles.out_buildroi;
        delete(gcf);% window is closed once the ROI is build
end
return